//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuzikDosyam_Prolab3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonelik> Abonelikler { get; set; }
        public virtual DbSet<Album> Albumler { get; set; }
        public virtual DbSet<AlbumSanatci> AlbumSanatcilari { get; set; }
        public virtual DbSet<AlbumSarki> AlbumSarkilari { get; set; }
        public virtual DbSet<CalmaListesi> CalmaListeleri { get; set; }
        public virtual DbSet<Kullanici> Kullanicilar { get; set; }
        public virtual DbSet<Sanatci> Sanatcilar { get; set; }
        public virtual DbSet<Sarki> Sarkilar { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Takipci> Takipciler { get; set; }
        public virtual DbSet<Tur> Turler { get; set; }
        public virtual DbSet<Ulke> Ulkeler { get; set; }
    }
}
