//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuzikDosyam_Prolab3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sarki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sarki()
        {
            this.Albumler = new HashSet<AlbumSarki>();
            this.CalmaListeleri = new HashSet<CalmaListesi>();
        }
    
        public int SarkiID { get; set; }
        public string Adi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> TurID { get; set; }
        public Nullable<int> Sure { get; set; }
        public Nullable<int> DinlenmeSayisi { get; set; }
        public Nullable<int> SanatciID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumSarki> Albumler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalmaListesi> CalmaListeleri { get; set; }
        public virtual Sanatci Sanatci { get; set; }
        public virtual Tur Tur { get; set; }
    }
}
