//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuzikDosyam_Prolab3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Takipci
    {
        public int Id { get; set; }
        public Nullable<int> TakipedenID { get; set; }
        public Nullable<int> TakipedilenID { get; set; }
    
        public virtual Kullanici TakipEden { get; set; }
        public virtual Kullanici TakipEdilen { get; set; }
    }
}
